on:
  pull_request:
    types: [open, reopened, synchronize]
    paths:
      - "**.json"
      - "**.js"
      - "**.jsx"
      - "**.mjs"
      - "**.ts"
      - "**.tsx"
      - "**.astro"
      - "**.lockb"
  push:
    branches:
      - main
    paths:
      - "**.json"
      - "**.js"
      - "**.jsx"
      - "**.mjs"
      - "**.ts"
      - "**.tsx"
      - "**.astro"
      - "**.lockb"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        name: setup bun
        with:
          bun-version: 1.0.22
      - name: install dependencies
        run: bun install
      - name: pull latest data
        run: bun run data
      - name: build site
        run: bun run build
      - name: deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --project-name=genocide-club site/dist
      - uses: actions/github-script@v6
        if: ${{ github.ref != 'refs/heads/main' }}
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview build deployed to: ${process.env.DEPLOYMENT_URL}`
            })
