on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        name: setup bun
        with:
          bun-version: 1.0.22
      - name: install dependencies
        run: bun install
      - name: pull latest data
        run: bun run data
      - name: build site
        run: bun run build
      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --project-name=genocide-club site/dist
