on:
  push:
    paths:
      - "**.json"
      - "**.js"
      - "**.jsx"
      - "**.mjs"
      - "**.ts"
      - "**.tsx"
      - "**.astro"
      - "**.lockb"
      - ".github/workflows/test.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        name: setup bun
        with:
          bun-version: 1.0.22
      - name: install dependencies
        run: bun install
      - name: run type check
        run: bun run types
      - name: setup data fixture
        run: mkdir -p site/src/generated && cp site/src/lib/server/__fixtures__/data.json site/src/generated/data.json
      - name: run unit tests
        run: bun run test
